apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: book
type: kubernetes.io/basic-auth
data:
  username: ZG9tY3JldGFu  # base64-encoded value of "domcretan"
  password: YWRtaW5fcm9vdF9reXIx  # base64-encoded value of "admin_root_kyr1"