name: Continuous Integration and Merge Workflow
run-name: Commit ${{ github.sha }} of branch ${{ github.ref}} by @${{ github.actor }}

on:
  push:
    branches:
      - develop

permissions:
  contents: write  # Adjust permissions as needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Compile and Test
        run: mvn clean verify

  create-release:
    needs: merge-to-develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Compile
        run: mvn clean package

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: dev-pre-release
          release_name: "Release ${{ github.sha }}"
          body: "Automatically generated release from ${{ github.sha }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: book-spring/target/book-spring-0.1.jar
          asset_name: book-spring-0.1.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
